# generated by Claude with prompts from Ginger. Last updated 7/23/2026. 
import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from datetime import datetime, timezone, timedelta
import sys, os, argparse

# ── Arguments ──────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Analyze PhishyMailbox CSV export")
parser.add_argument("csv")
parser.add_argument("--after",      default=None, help="Only include participants who started after this Eastern time. Format: YYYY-MM-DD or 'YYYY-MM-DD HH:MM'")
parser.add_argument("--before",     default=None, help="Only include participants who started before this Eastern time. Format: YYYY-MM-DD or 'YYYY-MM-DD HH:MM'")
parser.add_argument("--conditions", default=None, help="Path to a CSV with columns RandID and Condition")
parser.add_argument("--output",     default="phishy_analysis.xlsx")
args = parser.parse_args()

# ── Timezone ───────────────────────────────────────────────────────────────────
EASTERN = timezone(timedelta(hours=-4))  # EDT (UTC-4); change to -5 for EST in winter

def to_eastern(dt):
    return dt.astimezone(EASTERN) if pd.notna(dt) else pd.NaT

def parse_eastern(s):
    s = s.strip()
    try:    dt = datetime.strptime(s, "%Y-%m-%d %H:%M")
    except: dt = datetime.strptime(s, "%Y-%m-%d")
    return dt.replace(tzinfo=EASTERN)

# ── Load CSV ───────────────────────────────────────────────────────────────────
# use csv_path for output
csv_path = sys.argv[1] if len(sys.argv) > 1 else "export.csv"
df = pd.read_csv(args.csv)
df["At"] = pd.to_datetime(df["At"], utc=True, format="mixed")

# ── Load conditions (optional) ─────────────────────────────────────────────────
condition_map = {}
if args.conditions:
    cdf = pd.read_csv(args.conditions)
    cdf.columns = [c.strip() for c in cdf.columns]
    for _, row in cdf.iterrows():
        condition_map[str(row["RandID"]).strip()] = str(row["Condition"]).strip()
    print(f"  Conditions loaded for {len(condition_map)} participants.")

# ── Date filter ────────────────────────────────────────────────────────────────
filter_after  = parse_eastern(args.after)  if args.after  else None
filter_before = parse_eastern(args.before) if args.before else None

if filter_after or filter_before:
    started = df[df["Type"] == "started"][["Code","At"]]
    valid = set()
    for _, r in started.iterrows():
        t = r["At"]
        if filter_after  and t < filter_after:  continue
        if filter_before and t > filter_before: continue
        valid.add(r["Code"])
    df = df[df["Code"].isin(valid)]
    print(f"  Date filter applied — {len(valid)} participants match.")

# ── Email type helpers ─────────────────────────────────────────────────────────
def is_phish(e): return str(e).startswith("P")
def is_legit(e): return str(e).startswith("L")
def is_spam(e):  return str(e).startswith("S")

PHISH_CORRECT_FOLDERS = {"junk", "phishing", "trash"}
SPAM_CORRECT_FOLDERS  = {"junk", "trash", "phishing"}

# ── Email discovery ────────────────────────────────────────────────────────────
email_order, seen = [], set()
for _, row in df[df["Email-Backoffice-ID"].notna() & (df["Email-Backoffice-ID"] != "")].iterrows():
    eid = row["Email-Backoffice-ID"]
    if eid not in seen:
        email_order.append(eid)
        seen.add(eid)

participants = sorted(df["Code"].unique(), key=str)

def secs(s):
    if pd.isna(s) or s < 0: return ""
    s = int(s)
    return f"{s//60}m {s%60}s"

# Sub-columns per email type
PHISH_SUB = ["Folder", "Folder Correct", "Clicked Link", "Score", "Time Before First Click", "Time Before Move"]
SPAM_SUB  = ["Folder", "Folder Correct", "Clicked Link", "Score", "Time Before First Click", "Time Before Move"]
LEGIT_SUB = ["Folder", "Clicked Link", "Replied", "Score", "Time Before First Click", "Time Before Move"]

SUB_WIDTHS = {
    "Folder": 14, "Folder Correct": 13, "Clicked Link": 12,
    "Replied": 10, "Score": 11,
    "Time Before First Click": 18, "Time Before Move": 14,
}

rows = []
for code in participants:
    p = df[df["Code"] == code].sort_values("At")
    rid = str(p["RandID"].dropna().iloc[0]).strip() if p["RandID"].notna().any() else ""
    condition = condition_map.get(rid, "") if condition_map else ""

    started_rows  = p[p["Type"] == "started"]
    finished_rows = p[p["Type"] == "finished"]
    started_at    = started_rows["At"].iloc[0]  if not started_rows.empty  else pd.NaT
    finished_at   = finished_rows["At"].iloc[0] if not finished_rows.empty else pd.NaT

    started_et_str = to_eastern(started_at).strftime("%Y-%m-%d %H:%M ET") if pd.notna(started_at) else ""
    total_mins = round((finished_at - started_at).total_seconds() / 60, 1) \
        if pd.notna(started_at) and pd.notna(finished_at) else ""

    row = {
        "Participant Code":       code,
        "RandID":                 rid,
        "Condition":              condition,
        "Started At (ET)":        started_et_str,
        "Finished":               "Yes" if pd.notna(finished_at) else "No",
        "Total Time (mins)":      total_mins,
        "Phish: Folder Correct":  "",
        "Phish: No Link Clicked": "",
        "Phish Score":            "",
        "Spam: Folder Correct":   "",
        "Spam: No Link Clicked":  "",
        "Spam Score":             "",
        "Legit: Correct Folder":  "",
        "Legit: Clicked Link":    "",
        "Legit: Replied":         "",
        "Legit Score":            "",
        "Overall Score":          "",
    }

    phish_folder_correct = phish_no_click = phish_correct = phish_total = 0
    spam_folder_correct  = spam_no_click  = spam_correct  = spam_total  = 0
    legit_correct = legit_total = legit_clicked = legit_replied = 0

    for email_id in email_order:
        e = p[p["Email-Backoffice-ID"] == email_id].sort_values("At")

        if   is_phish(email_id): sub_cols = PHISH_SUB
        elif is_spam(email_id):  sub_cols = SPAM_SUB
        else:                     sub_cols = LEGIT_SUB

        if e.empty:
            for s in sub_cols:
                row[f"{email_id} | {s}"] = "not assigned" if s == "Folder" else ""
            continue

        moved        = e[e["Type"] == "email-moved"]
        views        = e[e["Type"] == "email-view"]
        clicks       = e[e["Type"] == "email-link-click"]
        replies      = e[e["Type"] == "email-send-reply"]

        folder       = moved["To Folder"].iloc[-1] if not moved.empty else "not moved"
        first_view   = views["At"].iloc[0]          if not views.empty  else pd.NaT
        first_click  = clicks["At"].iloc[0]         if not clicks.empty else pd.NaT
        clicked_link = "Yes" if not clicks.empty else "No"
        replied      = "Yes" if not replies.empty else "No"

        time_to_click = secs((first_click - first_view).total_seconds()) \
            if pd.notna(first_view) and pd.notna(first_click) else ""
        time_to_move  = secs((moved["At"].iloc[-1] - first_view).total_seconds()) \
            if pd.notna(first_view) and not moved.empty else ""

        if is_phish(email_id):
            phish_total += 1
            folder_ok  = folder.lower() in PHISH_CORRECT_FOLDERS if folder not in ("not moved","not assigned") else False
            no_click   = clicked_link == "No"
            score      = "Correct" if folder_ok and no_click else "Incorrect"
            if folder_ok:        phish_folder_correct += 1
            if no_click:         phish_no_click += 1
            if score=="Correct": phish_correct += 1

            row[f"{email_id} | Folder"]                  = folder
            row[f"{email_id} | Folder Correct"]          = "Yes" if folder_ok else "No"
            row[f"{email_id} | Clicked Link"]            = clicked_link
            row[f"{email_id} | Score"]                   = score
            row[f"{email_id} | Time Before First Click"] = time_to_click
            row[f"{email_id} | Time Before Move"]        = time_to_move

        elif is_spam(email_id):
            spam_total += 1
            folder_ok  = folder.lower() in SPAM_CORRECT_FOLDERS if folder not in ("not moved","not assigned") else False
            no_click   = clicked_link == "No"
            score      = "Correct" if folder_ok and no_click else "Incorrect"
            if folder_ok:        spam_folder_correct += 1
            if no_click:         spam_no_click += 1
            if score=="Correct": spam_correct += 1

            row[f"{email_id} | Folder"]                  = folder
            row[f"{email_id} | Folder Correct"]          = "Yes" if folder_ok else "No"
            row[f"{email_id} | Clicked Link"]            = clicked_link
            row[f"{email_id} | Score"]                   = score
            row[f"{email_id} | Time Before First Click"] = time_to_click
            row[f"{email_id} | Time Before Move"]        = time_to_move

        elif is_legit(email_id):
            legit_total += 1
            folder_wrong = folder.lower() in PHISH_CORRECT_FOLDERS if folder not in ("not moved","not assigned") else False
            score = "Incorrect" if folder_wrong else "Correct"
            if score=="Correct":      legit_correct += 1
            if clicked_link == "Yes": legit_clicked += 1
            if replied == "Yes":      legit_replied += 1

            row[f"{email_id} | Folder"]                  = folder
            row[f"{email_id} | Clicked Link"]            = clicked_link
            row[f"{email_id} | Replied"]                 = replied
            row[f"{email_id} | Score"]                   = score
            row[f"{email_id} | Time Before First Click"] = time_to_click
            row[f"{email_id} | Time Before Move"]        = time_to_move

    row["Phish: Folder Correct"]  = f"{phish_folder_correct}/{phish_total}"
    row["Phish: No Link Clicked"] = f"{phish_no_click}/{phish_total}"
    row["Phish Score"]            = f"{phish_correct}/{phish_total}"
    row["Spam: Folder Correct"]   = f"{spam_folder_correct}/{spam_total}"
    row["Spam: No Link Clicked"]  = f"{spam_no_click}/{spam_total}"
    row["Spam Score"]             = f"{spam_correct}/{spam_total}"
    row["Legit: Correct Folder"]  = f"{legit_correct}/{legit_total}"
    row["Legit: Clicked Link"]    = f"{legit_clicked}/{legit_total}"
    row["Legit: Replied"]         = f"{legit_replied}/{legit_total}"
    row["Legit Score"]            = f"{legit_correct}/{legit_total}"
    total = phish_total + spam_total + legit_total
    row["Overall Score"] = f"{phish_correct+spam_correct+legit_correct}/{total}" if total else ""
    rows.append(row)

result_df = pd.DataFrame(rows)

# ── Excel styles ───────────────────────────────────────────────────────────────
HEADER_FILL    = PatternFill("solid", fgColor="1F4E79")
PHISH_FILL     = PatternFill("solid", fgColor="C00000")
SPAM_FILL      = PatternFill("solid", fgColor="833C00")
LEGIT_FILL     = PatternFill("solid", fgColor="375623")
SUMMARY_FILL   = PatternFill("solid", fgColor="404040")
ALT_FILL       = PatternFill("solid", fgColor="EBF3FB")
WHITE_FILL     = PatternFill("solid", fgColor="FFFFFF")
CORRECT_FILL   = PatternFill("solid", fgColor="E2EFDA")
INCORRECT_FILL = PatternFill("solid", fgColor="FFDDD9")
LEGIT_FLAG     = PatternFill("solid", fgColor="FFF2CC")
SPAM_FLAG      = PatternFill("solid", fgColor="FCE4D6")

WHITE_FONT  = Font(name="Arial", bold=True, color="FFFFFF", size=10)
BODY_FONT   = Font(name="Arial", size=10)
BOLD_FONT   = Font(name="Arial", bold=True, size=10)
GREEN_FONT  = Font(name="Arial", bold=True, color="375623", size=10)
RED_FONT    = Font(name="Arial", bold=True, color="C00000", size=10)
AMBER_FONT  = Font(name="Arial", bold=True, color="7F6000", size=10)
ORANGE_FONT = Font(name="Arial", bold=True, color="833C00", size=10)
CENTER      = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT        = Alignment(horizontal="left",   vertical="center", wrap_text=True)

cols      = list(result_df.columns)
meta_cols = 17

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Participant Summary"

# Row 1 — email group headers
ws.append([""] * len(cols))
col_idx = meta_cols + 1
for email_id in email_order:
    sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    end_col  = col_idx + len(sub_cols) - 1
    ws.merge_cells(start_row=1, start_column=col_idx, end_row=1, end_column=end_col)
    cell       = ws.cell(row=1, column=col_idx)
    cell.value = email_id
    cell.fill  = PHISH_FILL if is_phish(email_id) else (SPAM_FILL if is_spam(email_id) else LEGIT_FILL)
    cell.font  = WHITE_FONT
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    col_idx += len(sub_cols)

# Row 2 — sub-headers
sub_headers = cols[:meta_cols] + [c.split(" | ")[1] for c in cols[meta_cols:]]
ws.append(sub_headers)
for i in range(1, len(cols) + 1):
    cell      = ws.cell(row=2, column=i)
    cell.fill = SUMMARY_FILL if i <= meta_cols else HEADER_FILL
    cell.font = WHITE_FONT
    cell.alignment = CENTER

# Data rows
for r_idx, row_data in enumerate(result_df.itertuples(index=False), start=3):
    base_fill = ALT_FILL if r_idx % 2 == 0 else WHITE_FILL
    for c_idx, val in enumerate(row_data, start=1):
        cell       = ws.cell(row=r_idx, column=c_idx)
        cell.value = val
        cell.alignment = CENTER if c_idx > meta_cols else LEFT
        col_name   = cols[c_idx - 1]
        email_name = col_name.split(" | ")[0] if " | " in col_name else ""

        if "| Score" in col_name:
            if val == "Correct":
                cell.fill, cell.font = CORRECT_FILL, GREEN_FONT
            elif val == "Incorrect":
                cell.fill, cell.font = INCORRECT_FILL, RED_FONT
            else:
                cell.fill, cell.font = base_fill, BODY_FONT

        elif "| Folder Correct" in col_name:
            if val == "Yes":
                cell.fill, cell.font = CORRECT_FILL, GREEN_FONT
            elif val == "No":
                cell.fill, cell.font = INCORRECT_FILL, RED_FONT
            else:
                cell.fill, cell.font = base_fill, BODY_FONT

        elif "| Clicked Link" in col_name and val == "Yes":
            if is_phish(email_name):
                cell.fill, cell.font = INCORRECT_FILL, RED_FONT
            elif is_spam(email_name):
                cell.fill, cell.font = SPAM_FLAG, ORANGE_FONT
            else:
                cell.fill, cell.font = LEGIT_FLAG, AMBER_FONT

        elif "| Replied" in col_name and val == "Yes":
            cell.fill, cell.font = LEGIT_FLAG, AMBER_FONT

        elif c_idx <= meta_cols:
            cell.fill, cell.font = base_fill, BOLD_FONT
        else:
            cell.fill, cell.font = base_fill, BODY_FONT

# Column widths
meta_widths = [18, 10, 14, 22, 10, 16, 14, 12, 14, 12, 12, 14, 14, 12, 12, 14, 14]
for i, w in enumerate(meta_widths, start=1):
    ws.column_dimensions[get_column_letter(i)].width = w
for i, col in enumerate(cols[meta_cols:], start=meta_cols + 1):
    sub = col.split(" | ")[1]
    ws.column_dimensions[get_column_letter(i)].width = SUB_WIDTHS.get(sub, 14)

ws.row_dimensions[1].height = 60
ws.row_dimensions[2].height = 40
ws.freeze_panes = f"{get_column_letter(meta_cols + 1)}3"

# ── Legend sheet ───────────────────────────────────────────────────────────────
ls = wb.create_sheet("Legend")
legend_rows = [
    ("Color",                     "Meaning"),
    ("Red email header",          "Phishing email (starts with P)"),
    ("Dark orange email header",  "Spam email (starts with S)"),
    ("Green email header",        "Legitimate email (starts with L)"),
    ("Green Score / Folder cell", "Correct"),
    ("Red Score / Folder cell",   "Incorrect"),
    ("Light orange Clicked Link", "Spam link click — flag for review (possible unsubscribe)"),
    ("Yellow Clicked / Replied",  "Legit link click or reply — informational only"),
    ("", ""),
    ("Phishing scoring",          ""),
    ("Folder Correct = Yes",      "Moved to Junk, Phishing, or Trash"),
    ("Folder Correct = No",       "Moved to any other folder, or not moved"),
    ("Clicked Link = Yes (red)",  "Clicked a link — always Incorrect regardless of folder"),
    ("Score = Correct",           "Folder correct AND no link clicked"),
    ("Score = Incorrect",         "Wrong folder OR clicked a link"),
    ("", ""),
    ("Spam scoring",              ""),
    ("Folder Correct = Yes",      "Moved to Junk, Trash, or Phishing"),
    ("Folder Correct = No",       "Moved to any other folder, or not moved"),
    ("Clicked Link (orange)",     "Flagged for review — may indicate unsubscribe attempt"),
    ("Score = Correct",           "Folder correct AND no link clicked"),
    ("Score = Incorrect",         "Wrong folder OR clicked a link"),
    ("", ""),
    ("Legit scoring",             ""),
    ("Score = Correct",           "Moved to any folder except Junk, Phishing, or Trash"),
    ("Score = Incorrect",         "Moved to Junk, Phishing, or Trash"),
    ("Clicked Link (yellow)",     "Informational only — does not affect score"),
    ("Replied (yellow)",          "Informational only — does not affect score"),
    ("", ""),
    ("Summary columns",           ""),
    ("Phish: Folder Correct",     "How many phish emails moved to correct folder (e.g. 4/5)"),
    ("Phish: No Link Clicked",    "How many phish emails had no link click (e.g. 3/5)"),
    ("Phish Score",               "Phish emails fully correct — right folder AND no click"),
    ("Spam: Folder Correct",      "How many spam emails moved to correct folder"),
    ("Spam: No Link Clicked",     "How many spam emails had no link click"),
    ("Spam Score",                "Spam emails fully correct — right folder AND no click"),
    ("Legit: Correct Folder",     "How many legit emails not wrongly flagged as phishing"),
    ("Legit: Clicked Link",       "How many legit emails had a link click (informational)"),
    ("Legit: Replied",            "How many legit emails had a reply (informational)"),
    ("", ""),
    ("Conditions",                ""),
    ("--conditions file.csv",     "CSV with columns RandID and Condition. Script works without it — Condition column will be blank."),
    ("", ""),
    ("Date filtering",            ""),
    ("--after 'YYYY-MM-DD'",      "Include participants who started on or after this date (Eastern time)"),
    ("--after 'YYYY-MM-DD HH:MM'","Same but with a specific time, e.g. --after '2026-07-18 13:00'"),
    ("--before 'YYYY-MM-DD HH:MM'","Include participants who started before this date/time"),
    ("Both flags together",       "Isolate one session, e.g. --after '2026-07-18' --before '2026-07-19'"),
    ("--output filename.xlsx",    "Custom output path. Default: phishy_analysis.xlsx in current directory"),
    ("", ""),
    ("Timezone note",             "All times are Eastern (EDT = UTC-4 in summer). Change EASTERN in script to UTC-5 for winter EST."),
]
for r, (a, b) in enumerate(legend_rows, start=1):
    ls.cell(row=r, column=1, value=a).font = Font(name="Arial", bold=True, size=10)
    ls.cell(row=r, column=2, value=b).font = Font(name="Arial", size=10)
ls.column_dimensions["A"].width = 32
ls.column_dimensions["B"].width = 70

# Get output directory
OUTPUT_DIR = csv_path 
DESCRIPTION = 'results/CBDR_7-20_detailed'
# Add run date to output filenames
run_date = datetime.now().strftime('%Y-%m-%d')
DESCRIPTION = f'{DESCRIPTION}__{run_date}.xlsx'
out_path = DESCRIPTION
os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)


wb.save(out_path)
print(f"✓ Saved to {out_path}")
print(f"  {len(rows)} participants × {len(email_order)} emails")
