# generated by Claude with prompts from Ginger. Last updated 7/23/2026. 
import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from datetime import datetime, timezone
import sys
import os

# ── Load CSV ──────────────────────────────────────────────────────────────────
csv_path = sys.argv[1] if len(sys.argv) > 1 else "export.csv"
df = pd.read_csv(csv_path)
df["At"] = pd.to_datetime(df["At"], utc=True)

# ── Discover all emails (in order of first appearance) ────────────────────────
email_order = []
seen = set()
for _, row in df[df["Email-Backoffice-ID"].notna() & (df["Email-Backoffice-ID"] != "")].iterrows():
    eid = row["Email-Backoffice-ID"]
    if eid not in seen:
        email_order.append(eid)
        seen.add(eid)

participants = sorted(df["Code"].unique(), key=lambda x: str(x))

# ── Build per-participant rows ─────────────────────────────────────────────────
def seconds_to_mmss(s):
    if pd.isna(s) or s < 0:
        return ""
    s = int(s)
    return f"{s // 60}m {s % 60}s"

rows = []
for code in participants:
    p = df[df["Code"] == code].sort_values("At")
    rid = p["RandID"].dropna().iloc[0] if p["RandID"].notna().any() else ""

    started_rows = p[p["Type"] == "started"]
    started_at = started_rows["At"].iloc[0] if not started_rows.empty else pd.NaT

    finished_rows = p[p["Type"] == "finished"]
    finished_at = finished_rows["At"].iloc[0] if not finished_rows.empty else pd.NaT

    if pd.notna(started_at) and pd.notna(finished_at):
        total_mins = round((finished_at - started_at).total_seconds() / 60, 1)
    else:
        total_mins = ""

    row = {
        "Participant Code": code,
        "RandID": rid,
        "Started At (UTC)": started_at.strftime("%Y-%m-%d %H:%M:%S") if pd.notna(started_at) else "",
        "Finished": "Yes" if pd.notna(finished_at) else "No",
        "Total Time (mins)": total_mins,
    }

    for email_id in email_order:
        e = p[p["Email-Backoffice-ID"] == email_id].sort_values("At")
        if e.empty:
            row[f"{email_id} | Folder"] = "not assigned"
            row[f"{email_id} | Clicked Link"] = ""
            row[f"{email_id} | Replied"] = ""
            row[f"{email_id} | Time Before First Click (s)"] = ""
            row[f"{email_id} | Time Before Move (s)"] = ""
            continue

        # folder moved to
        moved = e[e["Type"] == "email-moved"]
        folder = moved["To Folder"].iloc[-1] if not moved.empty else "not moved"

        # first view time
        views = e[e["Type"] == "email-view"]
        first_view = views["At"].iloc[0] if not views.empty else pd.NaT

        # link clicks
        clicks = e[e["Type"] == "email-link-click"]
        clicked_link = "Yes" if not clicks.empty else "No"
        first_click = clicks["At"].iloc[0] if not clicks.empty else pd.NaT

        # replies
        replies = e[e["Type"] == "email-send-reply"]
        replied = "Yes" if not replies.empty else "No"

        # time from first view to first link click
        if pd.notna(first_view) and pd.notna(first_click):
            time_to_click = seconds_to_mmss((first_click - first_view).total_seconds())
        else:
            time_to_click = ""

        # time from first view to move
        if pd.notna(first_view) and not moved.empty:
            move_time = moved["At"].iloc[-1]
            time_to_move = seconds_to_mmss((move_time - first_view).total_seconds())
        else:
            time_to_move = ""

        row[f"{email_id} | Folder"] = folder
        row[f"{email_id} | Clicked Link"] = clicked_link
        row[f"{email_id} | Replied"] = replied
        row[f"{email_id} | Time Before First Click"] = time_to_click
        row[f"{email_id} | Time Before Move"] = time_to_move

    rows.append(row)

result_df = pd.DataFrame(rows)

# ── Write to Excel with formatting ────────────────────────────────────────────
out_path = "/mnt/user-data/outputs/phishy_analysis.xlsx"
os.makedirs(os.path.dirname(out_path), exist_ok=True)

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Participant Summary"

# Colors
HEADER_FILL    = PatternFill("solid", fgColor="1F4E79")  # dark blue
EMAIL_FILL     = PatternFill("solid", fgColor="2E75B6")  # mid blue
META_FILL      = PatternFill("solid", fgColor="404040")  # dark gray
WHITE_FONT     = Font(name="Arial", bold=True, color="FFFFFF", size=10)
BODY_FONT      = Font(name="Arial", size=10)
BOLD_FONT      = Font(name="Arial", bold=True, size=10)
ALT_FILL       = PatternFill("solid", fgColor="EBF3FB")  # light blue
CENTER         = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT           = Alignment(horizontal="left", vertical="center", wrap_text=True)

cols = list(result_df.columns)
meta_cols = 5  # Code, RandID, Started, Finished, Total Time

# ── Row 1: email group headers ─────────────────────────────────────────────────
ws.append([""] * meta_cols + [""] * (len(cols) - meta_cols))
for i, col in enumerate(cols[meta_cols:], start=meta_cols + 1):
    if "| Folder" in col:
        email_name = col.split(" | ")[0]
        # merge 5 cells per email (Folder, Clicked, Replied, TimeClick, TimeMove)
        start_col = i
        end_col = i + 4
        ws.merge_cells(start_row=1, start_column=start_col, end_row=1, end_column=end_col)
        cell = ws.cell(row=1, column=start_col)
        cell.value = email_name
        cell.fill = EMAIL_FILL
        cell.font = WHITE_FONT
        cell.alignment = CENTER

# ── Row 2: column sub-headers ─────────────────────────────────────────────────
sub_headers = cols[:meta_cols] + [c.split(" | ")[1] for c in cols[meta_cols:]]
ws.append(sub_headers)
for i, val in enumerate(sub_headers, start=1):
    cell = ws.cell(row=2, column=i)
    cell.value = val
    cell.fill = META_FILL if i <= meta_cols else HEADER_FILL
    cell.font = WHITE_FONT
    cell.alignment = CENTER

# ── Data rows ─────────────────────────────────────────────────────────────────
for r_idx, row_data in enumerate(result_df.itertuples(index=False), start=3):
    fill = ALT_FILL if r_idx % 2 == 0 else PatternFill("solid", fgColor="FFFFFF")
    for c_idx, val in enumerate(row_data, start=1):
        cell = ws.cell(row=r_idx, column=c_idx)
        cell.value = val
        cell.font = BOLD_FONT if c_idx <= meta_cols else BODY_FONT
        cell.fill = fill
        cell.alignment = CENTER if c_idx > meta_cols else LEFT

# ── Column widths ─────────────────────────────────────────────────────────────
ws.column_dimensions["A"].width = 18  # Code
ws.column_dimensions["B"].width = 10  # RandID
ws.column_dimensions["C"].width = 20  # Started
ws.column_dimensions["D"].width = 10  # Finished
ws.column_dimensions["E"].width = 16  # Total Time

sub_col_widths = {"Folder": 14, "Clicked Link": 12, "Replied": 10,
                  "Time Before First Click": 18, "Time Before Move": 14}
for i, col in enumerate(cols[meta_cols:], start=meta_cols + 1):
    sub = col.split(" | ")[1]
    ws.column_dimensions[get_column_letter(i)].width = sub_col_widths.get(sub, 14)

ws.row_dimensions[1].height = 60
ws.row_dimensions[2].height = 40
ws.freeze_panes = "F3"

wb.save(out_path)
print(f"✓ Saved to {out_path}")
print(f"  {len(rows)} participants × {len(email_order)} emails")
