# generated by Claude with prompts from Ginger. Last updated 7/27/2026. 
import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from datetime import datetime, timezone, timedelta
import sys, os, argparse

# ── Arguments ──────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Analyze PhishyMailbox CSV export")
parser.add_argument("csv")
parser.add_argument("--after",      default=None, help="Only include participants who started after this Eastern time. Format: YYYY-MM-DD or 'YYYY-MM-DD HH:MM'")
parser.add_argument("--before",     default=None, help="Only include participants who started before this Eastern time.")
parser.add_argument("--conditions", default=None, help="Path to a CSV with columns RandID and Condition")
parser.add_argument("--output",     default="phishy_analysis.xlsx")
args = parser.parse_args()

# ── Timezone ───────────────────────────────────────────────────────────────────
EASTERN = timezone(timedelta(hours=-4))  # EDT; change to -5 for EST in winter

def to_eastern(dt):
    return dt.astimezone(EASTERN) if pd.notna(dt) else pd.NaT

def parse_eastern(s):
    s = s.strip()
    try:    dt = datetime.strptime(s, "%Y-%m-%d %H:%M")
    except: dt = datetime.strptime(s, "%Y-%m-%d")
    return dt.replace(tzinfo=EASTERN)

# ── Load CSV ───────────────────────────────────────────────────────────────────
# use csv_path for output
csv_path = sys.argv[1] if len(sys.argv) > 1 else "export.csv"
df = pd.read_csv(args.csv)
df = pd.read_csv(args.csv)
df["At"] = pd.to_datetime(df["At"], utc=True, format="mixed")

# ── Conditions ─────────────────────────────────────────────────────────────────
condition_map = {}
all_conditions = []
if args.conditions:
    cdf = pd.read_csv(args.conditions)
    cdf.columns = [c.strip() for c in cdf.columns]
    for _, row in cdf.iterrows():
        condition_map[str(row["RandID"]).strip()] = str(row["Condition"]).strip()
    all_conditions = sorted(set(condition_map.values()))
    print(f"  Conditions loaded for {len(condition_map)} participants: {all_conditions}")

# ── Date filter ────────────────────────────────────────────────────────────────
filter_after  = parse_eastern(args.after)  if args.after  else None
filter_before = parse_eastern(args.before) if args.before else None
if filter_after or filter_before:
    started = df[df["Type"] == "started"][["Code","At"]]
    valid = set()
    for _, r in started.iterrows():
        t = r["At"]
        if filter_after  and t < filter_after:  continue
        if filter_before and t > filter_before: continue
        valid.add(r["Code"])
    df = df[df["Code"].isin(valid)]
    print(f"  Date filter applied — {len(valid)} participants match.")

def is_phish(e): return str(e).startswith("P")
def is_legit(e): return str(e).startswith("L")
def is_spam(e):  return str(e).startswith("S")

# ── Email discovery ────────────────────────────────────────────────────────────
email_order, seen = [], set()
for _, row in df[df["Email-Backoffice-ID"].notna() & (df["Email-Backoffice-ID"] != "")].iterrows():
    eid = row["Email-Backoffice-ID"]
    if eid not in seen:
        email_order.append(eid)
        seen.add(eid)

participants = sorted(df["Code"].unique(), key=str)

def secs(s):
    if pd.isna(s) or s < 0: return ""
    s = int(s)
    return f"{s//60}m {s%60}s"

PHISH_SUB = ["Clicked Link", "Score", "Replied", "Folder", "Time Before First Click", "Time Before Move"]
SPAM_SUB  = ["Clicked Link", "Replied", "Folder", "Time Before First Click", "Time Before Move"]
LEGIT_SUB = ["Clicked Link", "Replied", "Folder", "Time Before First Click", "Time Before Move"]

SUB_WIDTHS = {
    "Folder": 14, "Clicked Link": 12, "Replied": 10, "Score": 11,
    "Time Before First Click": 18, "Time Before Move": 14,
}

# Build column index map
meta_cols = 8  # +1 for Legit Flagged as Phish
email_col_map = {}
ci = meta_cols + 1
for email_id in email_order:
    sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    email_col_map[email_id] = {}
    for s in sub_cols:
        email_col_map[email_id][s] = ci
        ci += 1

# ── Build data rows ────────────────────────────────────────────────────────────
rows = []
for code in participants:
    p = df[df["Code"] == code].sort_values("At")
    rid = str(p["RandID"].dropna().iloc[0]).strip() if p["RandID"].notna().any() else ""
    condition = condition_map.get(rid, "") if condition_map else ""

    started_rows  = p[p["Type"] == "started"]
    finished_rows = p[p["Type"] == "finished"]
    started_at    = started_rows["At"].iloc[0]  if not started_rows.empty  else pd.NaT
    finished_at   = finished_rows["At"].iloc[0] if not finished_rows.empty else pd.NaT

    started_et_str = to_eastern(started_at).strftime("%Y-%m-%d %H:%M ET") if pd.notna(started_at) else ""
    total_mins = round((finished_at - started_at).total_seconds() / 60, 1) \
        if pd.notna(started_at) and pd.notna(finished_at) else ""

    row = {
        "Participant Code":        code,
        "RandID":                  rid,
        "Condition":               condition,
        "Started At (ET)":         started_et_str,
        "Finished":                "Yes" if pd.notna(finished_at) else "No",
        "Total Time (mins)":       total_mins,
        "Phish Score":             "",
        "Legit Flagged as Phish":  "",
    }

    phish_correct = phish_total = 0
    legit_flagged = 0

    for email_id in email_order:
        e = p[p["Email-Backoffice-ID"] == email_id].sort_values("At")
        sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)

        if e.empty:
            for s in sub_cols:
                row[f"{email_id} | {s}"] = "not assigned" if s == "Folder" else ""
            continue

        moved        = e[e["Type"] == "email-moved"]
        views        = e[e["Type"] == "email-view"]
        clicks       = e[e["Type"] == "email-link-click"]
        replies      = e[e["Type"] == "email-send-reply"]

        folder       = moved["To Folder"].iloc[-1] if not moved.empty else "not moved"
        first_view   = views["At"].iloc[0]          if not views.empty  else pd.NaT
        first_click  = clicks["At"].iloc[0]         if not clicks.empty else pd.NaT
        clicked_link = "Yes" if not clicks.empty else "No"
        replied      = "Yes" if not replies.empty else "No"

        time_to_click = secs((first_click - first_view).total_seconds()) \
            if pd.notna(first_view) and pd.notna(first_click) else ""
        time_to_move  = secs((moved["At"].iloc[-1] - first_view).total_seconds()) \
            if pd.notna(first_view) and not moved.empty else ""

        row[f"{email_id} | Folder"]                  = folder
        row[f"{email_id} | Clicked Link"]            = clicked_link
        row[f"{email_id} | Time Before First Click"] = time_to_click
        row[f"{email_id} | Time Before Move"]        = time_to_move

        if is_phish(email_id):
            phish_total += 1
            score = "Correct" if clicked_link == "No" else "Incorrect"
            if score == "Correct": phish_correct += 1
            row[f"{email_id} | Score"]   = score
            row[f"{email_id} | Replied"] = replied
        else:
            row[f"{email_id} | Replied"] = replied
            if is_legit(email_id) and folder == "Phishing":
                legit_flagged += 1

    row["Phish Score"]            = f"{phish_correct}/{phish_total}" if phish_total else ""
    row["Legit Flagged as Phish"] = legit_flagged
    rows.append(row)

result_df = pd.DataFrame(rows)

# Reorder columns to match SUB order exactly
meta_col_names = ["Participant Code","RandID","Condition","Started At (ET)","Finished",
                  "Total Time (mins)","Phish Score","Legit Flagged as Phish"]
email_cols = []
for email_id in email_order:
    sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    for s in sub_cols:
        email_cols.append(f"{email_id} | {s}")
result_df = result_df[meta_col_names + email_cols]

n_participants = len(rows)
data_start_row = 3
data_end_row   = 2 + n_participants
totals_start   = data_end_row + 1

all_folders = sorted(set(df[df["Type"]=="email-moved"]["To Folder"].dropna().unique()))

# Pre-compute email data lookup
email_data_lookup = {}
for email_id in email_order:
    p_email = df[df["Email-Backoffice-ID"] == email_id]
    lookup = {}
    for code in participants:
        p_code = p_email[p_email["Code"] == code]
        clicked = not p_code[p_code["Type"] == "email-link-click"].empty
        replied = not p_code[p_code["Type"] == "email-send-reply"].empty
        moved   = p_code[p_code["Type"] == "email-moved"]
        folder  = moved["To Folder"].iloc[-1] if not moved.empty else None
        # get rid for condition lookup
        p_full  = df[df["Code"] == code]
        rid     = str(p_full["RandID"].dropna().iloc[0]).strip() if p_full["RandID"].notna().any() else ""
        cond    = condition_map.get(rid, "") if condition_map else ""
        lookup[code] = {"clicked": clicked, "replied": replied, "folder": folder, "condition": cond}
    email_data_lookup[email_id] = lookup

# Also build per-participant phish scores for condition averaging
participant_phish_scores = {}
for row in rows:
    code = row["Participant Code"]
    score_str = row["Phish Score"]
    if score_str and "/" in str(score_str):
        num, den = score_str.split("/")
        participant_phish_scores[code] = int(num) / int(den) if int(den) > 0 else None
    else:
        participant_phish_scores[code] = None
# attach condition to score
p_rid_map = {}
for code in participants:
    p_full = df[df["Code"] == code]
    rid = str(p_full["RandID"].dropna().iloc[0]).strip() if p_full["RandID"].notna().any() else ""
    p_rid_map[code] = condition_map.get(rid, "") if condition_map else ""

# ── Styles ─────────────────────────────────────────────────────────────────────
HEADER_FILL    = PatternFill("solid", fgColor="1F4E79")
PHISH_FILL     = PatternFill("solid", fgColor="C00000")
SPAM_FILL      = PatternFill("solid", fgColor="833C00")
LEGIT_FILL     = PatternFill("solid", fgColor="375623")
SUMMARY_FILL   = PatternFill("solid", fgColor="404040")
TOTALS_HDR     = PatternFill("solid", fgColor="2E4057")
ALT_FILL       = PatternFill("solid", fgColor="EBF3FB")
WHITE_FILL     = PatternFill("solid", fgColor="FFFFFF")
CORRECT_FILL   = PatternFill("solid", fgColor="E2EFDA")
INCORRECT_FILL = PatternFill("solid", fgColor="FFDDD9")
LEGIT_FLAG     = PatternFill("solid", fgColor="FFF2CC")
SPAM_FLAG      = PatternFill("solid", fgColor="FCE4D6")
TOTALS_ALT     = PatternFill("solid", fgColor="E8EDF2")
COND_FILLS     = [
    PatternFill("solid", fgColor="1F4E79"),
    PatternFill("solid", fgColor="375623"),
    PatternFill("solid", fgColor="833C00"),
    PatternFill("solid", fgColor="2E4057"),
    PatternFill("solid", fgColor="C00000"),
    PatternFill("solid", fgColor="404040"),
    PatternFill("solid", fgColor="7F6000"),
    PatternFill("solid", fgColor="4B0082"),
]

WHITE_FONT   = Font(name="Arial", bold=True, color="FFFFFF", size=10)
BODY_FONT    = Font(name="Arial", size=10)
BOLD_FONT    = Font(name="Arial", bold=True, size=10)
GREEN_FONT   = Font(name="Arial", bold=True, color="375623", size=10)
RED_FONT     = Font(name="Arial", bold=True, color="C00000", size=10)
AMBER_FONT   = Font(name="Arial", bold=True, color="7F6000", size=10)
ORANGE_FONT  = Font(name="Arial", bold=True, color="833C00", size=10)
CENTER       = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT         = Alignment(horizontal="left",   vertical="center", wrap_text=True)
BLACK_SIDE   = Side(style="medium", color="000000")

cols = list(result_df.columns)

os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Participant Summary"

# ── Row 1: email group headers ─────────────────────────────────────────────────
ws.append([""] * len(cols))
col_idx = meta_cols + 1
for email_id in email_order:
    sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    end_col  = col_idx + len(sub_cols) - 1
    ws.merge_cells(start_row=1, start_column=col_idx, end_row=1, end_column=end_col)
    cell = ws.cell(row=1, column=col_idx)
    cell.value = email_id
    cell.fill  = PHISH_FILL if is_phish(email_id) else (SPAM_FILL if is_spam(email_id) else LEGIT_FILL)
    cell.font  = WHITE_FONT
    cell.alignment = CENTER
    col_idx += len(sub_cols)

# ── Row 2: sub-headers ─────────────────────────────────────────────────────────
sub_headers = cols[:meta_cols] + [c.split(" | ")[1] for c in cols[meta_cols:]]
ws.append(sub_headers)
for i in range(1, len(cols) + 1):
    cell = ws.cell(row=2, column=i)
    cell.fill = SUMMARY_FILL if i <= meta_cols else HEADER_FILL
    cell.font = WHITE_FONT
    cell.alignment = CENTER

# ── Data rows ──────────────────────────────────────────────────────────────────
for r_idx, row_data in enumerate(result_df.itertuples(index=False), start=3):
    base_fill = ALT_FILL if r_idx % 2 == 0 else WHITE_FILL
    for c_idx, val in enumerate(row_data, start=1):
        cell = ws.cell(row=r_idx, column=c_idx)
        cell.value = val
        cell.alignment = CENTER if c_idx > meta_cols else LEFT
        col_name   = cols[c_idx - 1]
        email_name = col_name.split(" | ")[0] if " | " in col_name else ""

        if "| Score" in col_name:
            if val == "Correct":     cell.fill, cell.font = CORRECT_FILL, GREEN_FONT
            elif val == "Incorrect": cell.fill, cell.font = INCORRECT_FILL, RED_FONT
            else:                    cell.fill, cell.font = base_fill, BODY_FONT
        elif "| Clicked Link" in col_name and val == "Yes":
            if is_phish(email_name):  cell.fill, cell.font = INCORRECT_FILL, RED_FONT
            elif is_spam(email_name): cell.fill, cell.font = SPAM_FLAG, ORANGE_FONT
            else:                     cell.fill, cell.font = LEGIT_FLAG, AMBER_FONT
        elif "| Replied" in col_name and val == "Yes":
            cell.fill, cell.font = LEGIT_FLAG, AMBER_FONT
        elif col_name == "Legit Flagged as Phish" and isinstance(val, int) and val > 0:
            cell.fill, cell.font = INCORRECT_FILL, RED_FONT
        elif c_idx <= meta_cols:
            cell.fill, cell.font = base_fill, BOLD_FONT
        else:
            cell.fill, cell.font = base_fill, BODY_FONT

# ── Totals section ─────────────────────────────────────────────────────────────
totals_metrics = [
    ("# Clicked",     "clicked"),
    ("# Not Clicked", "not_clicked"),
    ("% Clicked",     "pct_clicked"),
    ("",              "blank1"),
]
for folder in all_folders:
    totals_metrics.append((f"# in {folder}", f"folder_{folder}"))
totals_metrics += [
    ("",              "blank2"),
    ("# Replied",     "replied"),
    ("# Not Replied", "not_replied"),
    ("% Replied",     "pct_replied"),
]

ws.cell(row=totals_start, column=1, value="TOTALS").fill = TOTALS_HDR
ws.cell(row=totals_start, column=1).font = WHITE_FONT
ws.cell(row=totals_start, column=1).alignment = LEFT

metric_row = {}
r = totals_start + 1
for label, key in totals_metrics:
    metric_row[key] = r
    if label:
        c = ws.cell(row=r, column=1)
        c.value = label
        c.font  = BOLD_FONT
        c.fill  = TOTALS_ALT if r % 2 == 0 else WHITE_FILL
        c.alignment = LEFT
    r += 1

for email_id in email_order:
    sub_cols    = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    has_replied = "Replied" in sub_cols
    lookup      = email_data_lookup[email_id]
    ci_click    = email_col_map[email_id]["Clicked Link"]
    ci_folder   = email_col_map[email_id]["Folder"]
    ci_reply    = email_col_map[email_id]["Replied"] if has_replied else None

    n_clicked     = sum(1 for v in lookup.values() if v["clicked"])
    n_not_clicked = sum(1 for v in lookup.values() if not v["clicked"])
    pct_clicked   = round(n_clicked / (n_clicked + n_not_clicked), 4) if (n_clicked + n_not_clicked) > 0 else ""

    cell = ws.cell(row=metric_row["clicked"],     column=ci_click)
    cell.value, cell.font, cell.alignment = n_clicked, BODY_FONT, CENTER
    cell = ws.cell(row=metric_row["not_clicked"], column=ci_click)
    cell.value, cell.font, cell.alignment = n_not_clicked, BODY_FONT, CENTER
    cell = ws.cell(row=metric_row["pct_clicked"], column=ci_click)
    cell.value, cell.font, cell.alignment = pct_clicked, BODY_FONT, CENTER
    if pct_clicked != "": cell.number_format = "0%"

    for folder in all_folders:
        count = sum(1 for v in lookup.values() if v["folder"] == folder)
        cell  = ws.cell(row=metric_row[f"folder_{folder}"], column=ci_folder)
        cell.value, cell.font, cell.alignment = count, BODY_FONT, CENTER

    if has_replied and ci_reply:
        n_replied     = sum(1 for v in lookup.values() if v["replied"])
        n_not_replied = sum(1 for v in lookup.values() if not v["replied"])
        pct_replied   = round(n_replied / (n_replied + n_not_replied), 4) if (n_replied + n_not_replied) > 0 else ""
        cell = ws.cell(row=metric_row["replied"],     column=ci_reply)
        cell.value, cell.font, cell.alignment = n_replied, BODY_FONT, CENTER
        cell = ws.cell(row=metric_row["not_replied"], column=ci_reply)
        cell.value, cell.font, cell.alignment = n_not_replied, BODY_FONT, CENTER
        cell = ws.cell(row=metric_row["pct_replied"], column=ci_reply)
        cell.value, cell.font, cell.alignment = pct_replied, BODY_FONT, CENTER
        if pct_replied != "": cell.number_format = "0%"

# ── Column widths + borders ────────────────────────────────────────────────────
meta_widths = [18, 10, 14, 22, 10, 16, 14, 20]
for i, w in enumerate(meta_widths, start=1):
    ws.column_dimensions[get_column_letter(i)].width = w
for i, col in enumerate(cols[meta_cols:], start=meta_cols + 1):
    sub = col.split(" | ")[1]
    ws.column_dimensions[get_column_letter(i)].width = SUB_WIDTHS.get(sub, 14)

ws.row_dimensions[1].height = 60
ws.row_dimensions[2].height = 40
ws.freeze_panes = f"{get_column_letter(meta_cols + 1)}3"

for email_id in email_order:
    sub_cols  = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
    first_col = email_col_map[email_id][sub_cols[0]]
    last_col  = email_col_map[email_id][sub_cols[-1]]
    for row in range(1, ws.max_row + 1):
        lc = ws.cell(row=row, column=first_col)
        rc = ws.cell(row=row, column=last_col)
        lc.border = Border(left=BLACK_SIDE, right=lc.border.right if lc.border else Side())
        rc.border = Border(left=rc.border.left if rc.border else Side(), right=BLACK_SIDE)

# ── Summary tab ────────────────────────────────────────────────────────────────
ss = wb.create_sheet("Summary")

ss.cell(row=1, column=1, value="Category").fill = SUMMARY_FILL
ss.cell(row=1, column=1).font = WHITE_FONT
ss.cell(row=1, column=1).alignment = CENTER
ss.cell(row=1, column=2, value="Metric").fill = SUMMARY_FILL
ss.cell(row=1, column=2).font = WHITE_FONT
ss.cell(row=1, column=2).alignment = CENTER

for e_idx, email_id in enumerate(email_order, start=3):
    c = ss.cell(row=1, column=e_idx)
    c.value = email_id
    c.fill  = PHISH_FILL if is_phish(email_id) else (SPAM_FILL if is_spam(email_id) else LEGIT_FILL)
    c.font  = WHITE_FONT
    c.alignment = CENTER

summary_metrics = [
    ("Clicked",  "# Clicked",     "clicked",     "Clicked Link"),
    ("Clicked",  "# Not Clicked", "not_clicked", "Clicked Link"),
    ("Clicked",  "% Clicked",     "pct_clicked", "Clicked Link"),
]
for folder in all_folders:
    summary_metrics.append(("Folders", f"# in {folder}", f"folder_{folder}", "Folder"))
summary_metrics += [
    ("Replies", "# Replied",     "replied",     "Replied"),
    ("Replies", "# Not Replied", "not_replied", "Replied"),
    ("Replies", "% Replied",     "pct_replied", "Replied"),
]

category_rows = {}
for r_idx, (cat, label, key, sub) in enumerate(summary_metrics, start=2):
    if cat not in category_rows:
        category_rows[cat] = [r_idx, r_idx]
    else:
        category_rows[cat][1] = r_idx

section_last_rows = {}
for r_idx, (cat, label, key, sub) in enumerate(summary_metrics, start=2):
    section_last_rows[cat] = r_idx

for r_idx, (cat, label, key, sub) in enumerate(summary_metrics, start=2):
    base = TOTALS_ALT if r_idx % 2 == 0 else WHITE_FILL
    ca = ss.cell(row=r_idx, column=1)
    ca.fill, ca.alignment = base, CENTER
    cb = ss.cell(row=r_idx, column=2)
    cb.value = label
    cb.font, cb.fill, cb.alignment = BOLD_FONT, base, LEFT

    for e_idx, email_id in enumerate(email_order, start=3):
        sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
        c = ss.cell(row=r_idx, column=e_idx)
        c.fill, c.alignment, c.font = base, CENTER, BODY_FONT

        if sub not in sub_cols:
            c.value = "N/A"
            continue

        lookup = email_data_lookup[email_id]
        n_total = len(lookup)

        if key == "clicked":
            c.value = sum(1 for v in lookup.values() if v["clicked"])
        elif key == "not_clicked":
            c.value = sum(1 for v in lookup.values() if not v["clicked"])
        elif key == "pct_clicked":
            n = sum(1 for v in lookup.values() if v["clicked"])
            c.value = round(n / n_total, 4) if n_total > 0 else ""
            if c.value != "": c.number_format = "0%"
        elif key.startswith("folder_"):
            folder = key[len("folder_"):]
            count  = sum(1 for v in lookup.values() if v["folder"] == folder)
            pct    = round(count / n_total * 100) if n_total > 0 else 0
            c.value = f"{count} ({pct}%)"
        elif key == "replied":
            c.value = sum(1 for v in lookup.values() if v["replied"])
        elif key == "not_replied":
            c.value = sum(1 for v in lookup.values() if not v["replied"])
        elif key == "pct_replied":
            n = sum(1 for v in lookup.values() if v["replied"])
            c.value = round(n / n_total, 4) if n_total > 0 else ""
            if c.value != "": c.number_format = "0%"

for cat, (r_start, r_end) in category_rows.items():
    if r_start < r_end:
        ss.merge_cells(start_row=r_start, start_column=1, end_row=r_end, end_column=1)
    c = ss.cell(row=r_start, column=1)
    c.value = cat
    c.font  = WHITE_FONT
    c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    c.fill  = TOTALS_HDR if cat == "Clicked" else (LEGIT_FILL if cat == "Replies" else SUMMARY_FILL)

for cat, last_row in section_last_rows.items():
    for col in range(1, len(email_order) + 3):
        cell = ss.cell(row=last_row, column=col)
        cell.border = Border(
            left=cell.border.left, right=cell.border.right, top=cell.border.top,
            bottom=Side(style="medium", color="000000")
        )

ss.column_dimensions["A"].width = 12
ss.column_dimensions["B"].width = 18
for i in range(3, len(email_order) + 3):
    ss.column_dimensions[get_column_letter(i)].width = 22
ss.row_dimensions[1].height = 60
ss.freeze_panes = "C2"

# ── Condition tab (only if --conditions provided) ──────────────────────────────
if args.conditions and all_conditions:
    cs = wb.create_sheet("By Condition")

    # Build column structure: col A=Category, col B=Metric,
    # then for each email: one col per condition
    # Header row 1: email group headers (merged across conditions)
    # Header row 2: condition sub-headers

    n_conds = len(all_conditions)
    cs.cell(row=1, column=1, value="Category").fill = SUMMARY_FILL
    cs.cell(row=1, column=1).font = WHITE_FONT
    cs.cell(row=1, column=1).alignment = CENTER
    cs.cell(row=2, column=1, value="Category").fill = SUMMARY_FILL
    cs.cell(row=2, column=1).font = WHITE_FONT
    cs.cell(row=2, column=1).alignment = CENTER
    cs.merge_cells(start_row=1, start_column=1, end_row=2, end_column=1)

    cs.cell(row=1, column=2, value="Metric").fill = SUMMARY_FILL
    cs.cell(row=1, column=2).font = WHITE_FONT
    cs.cell(row=1, column=2).alignment = CENTER
    cs.cell(row=2, column=2, value="Metric").fill = SUMMARY_FILL
    cs.cell(row=2, column=2).font = WHITE_FONT
    cs.cell(row=2, column=2).alignment = CENTER
    cs.merge_cells(start_row=1, start_column=2, end_row=2, end_column=2)

    # Email group headers in row 1, condition sub-headers in row 2
    col_start = 3
    email_cond_col_map = {}  # email_id -> condition -> col index
    for email_id in email_order:
        end_col = col_start + n_conds - 1
        cs.merge_cells(start_row=1, start_column=col_start, end_row=1, end_column=end_col)
        cell = cs.cell(row=1, column=col_start)
        cell.value = email_id
        cell.fill  = PHISH_FILL if is_phish(email_id) else (SPAM_FILL if is_spam(email_id) else LEGIT_FILL)
        cell.font  = WHITE_FONT
        cell.alignment = CENTER

        email_cond_col_map[email_id] = {}
        for c_idx, cond in enumerate(all_conditions):
            col = col_start + c_idx
            cell = cs.cell(row=2, column=col)
            cell.value = f"Cond {cond}"
            cell.fill  = COND_FILLS[c_idx % len(COND_FILLS)]
            cell.font  = WHITE_FONT
            cell.alignment = CENTER
            email_cond_col_map[email_id][cond] = col

        col_start += n_conds

    # Condition summary metrics (same as Summary tab)
    cond_metrics = [
        ("Clicked",  "# Clicked",     "clicked",     "Clicked Link"),
        ("Clicked",  "# Not Clicked", "not_clicked", "Clicked Link"),
        ("Clicked",  "% Clicked",     "pct_clicked", "Clicked Link"),
    ]
    for folder in all_folders:
        cond_metrics.append(("Folders", f"# in {folder}", f"folder_{folder}", "Folder"))
    cond_metrics += [
        ("Replies", "# Replied",     "replied",     "Replied"),
        ("Replies", "# Not Replied", "not_replied", "Replied"),
        ("Replies", "% Replied",     "pct_replied", "Replied"),
    ]

    # Add average phish score row at the end
    cond_metrics.append(("Score", "Avg Phish Score", "avg_phish_score", None))

    cat_rows_cond = {}
    sect_last_cond = {}
    for r_idx, (cat, label, key, sub) in enumerate(cond_metrics, start=3):
        if cat not in cat_rows_cond:
            cat_rows_cond[cat] = [r_idx, r_idx]
        else:
            cat_rows_cond[cat][1] = r_idx
        sect_last_cond[cat] = r_idx

    for r_idx, (cat, label, key, sub) in enumerate(cond_metrics, start=3):
        base = TOTALS_ALT if r_idx % 2 == 0 else WHITE_FILL

        ca = cs.cell(row=r_idx, column=1)
        ca.fill, ca.alignment = base, CENTER

        cb = cs.cell(row=r_idx, column=2)
        cb.value = label
        cb.font, cb.fill, cb.alignment = BOLD_FONT, base, LEFT

        for email_id in email_order:
            sub_cols = PHISH_SUB if is_phish(email_id) else (SPAM_SUB if is_spam(email_id) else LEGIT_SUB)
            lookup   = email_data_lookup[email_id]

            for cond in all_conditions:
                col = email_cond_col_map[email_id][cond]
                c   = cs.cell(row=r_idx, column=col)
                c.fill, c.alignment, c.font = base, CENTER, BODY_FONT

                # Filter lookup to this condition
                cond_lookup = {code: v for code, v in lookup.items() if v["condition"] == cond}
                n_cond = len(cond_lookup)

                if key == "avg_phish_score":
                    if not is_phish(email_id):
                        c.value = "N/A"
                        continue
                    # avg phish score across all phish emails for this condition
                    scores = [participant_phish_scores.get(code) for code, v in
                              {co: v for co, v in
                               {co2: {"condition": p_rid_map.get(co2,"")} for co2 in participants}.items()
                               if v["condition"] == cond}.items()
                              if participant_phish_scores.get(code) is not None]
                    # simpler: just compute once per cond, not per email
                    c.value = "→"  # placeholder, filled after loop
                    continue

                if sub and sub not in sub_cols:
                    c.value = "N/A"
                    continue

                if n_cond == 0:
                    c.value = 0
                    continue

                if key == "clicked":
                    c.value = sum(1 for v in cond_lookup.values() if v["clicked"])
                elif key == "not_clicked":
                    c.value = sum(1 for v in cond_lookup.values() if not v["clicked"])
                elif key == "pct_clicked":
                    n = sum(1 for v in cond_lookup.values() if v["clicked"])
                    c.value = round(n / n_cond, 4) if n_cond > 0 else ""
                    if c.value != "": c.number_format = "0%"
                elif key.startswith("folder_"):
                    folder = key[len("folder_"):]
                    count  = sum(1 for v in cond_lookup.values() if v["folder"] == folder)
                    pct    = round(count / n_cond * 100) if n_cond > 0 else 0
                    c.value = f"{count} ({pct}%)"
                elif key == "replied":
                    c.value = sum(1 for v in cond_lookup.values() if v["replied"])
                elif key == "not_replied":
                    c.value = sum(1 for v in cond_lookup.values() if not v["replied"])
                elif key == "pct_replied":
                    n = sum(1 for v in cond_lookup.values() if v["replied"])
                    c.value = round(n / n_cond, 4) if n_cond > 0 else ""
                    if c.value != "": c.number_format = "0%"

    # Fill average phish score row (one merged value per condition spanning all email cols)
    avg_score_row = [r for r, (cat, label, key, sub) in enumerate(cond_metrics, start=3) if key == "avg_phish_score"][0]
    base_r = TOTALS_ALT if avg_score_row % 2 == 0 else WHITE_FILL
    for cond in all_conditions:
        scores = [participant_phish_scores[code] for code in participants
                  if p_rid_map.get(code) == cond and participant_phish_scores.get(code) is not None]
        avg = round(sum(scores) / len(scores), 4) if scores else None

        all_cond_cols = sorted([email_cond_col_map[eid][cond] for eid in email_order])

        # Style all cells and write value only in first email col, blank elsewhere
        for i, col in enumerate(all_cond_cols):
            cell = cs.cell(row=avg_score_row, column=col)
            cell.fill = base_r
            cell.alignment = CENTER
            if i == 0:
                cell.value = avg if avg is not None else "N/A"
                if avg is not None: cell.number_format = "0%"
                cell.font = BOLD_FONT
            else:
                cell.value = None
                cell.font = BODY_FONT

    # Category merges and section borders
    for cat, (r_start, r_end) in cat_rows_cond.items():
        if r_start < r_end:
            cs.merge_cells(start_row=r_start, start_column=1, end_row=r_end, end_column=1)
        c = cs.cell(row=r_start, column=1)
        c.value = cat
        c.font  = WHITE_FONT
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        c.fill  = TOTALS_HDR if cat == "Clicked" else \
                  (LEGIT_FILL if cat == "Replies" else \
                  (PHISH_FILL if cat == "Score" else SUMMARY_FILL))

    for cat, last_row in sect_last_cond.items():
        for col in range(1, col_start):
            cell = cs.cell(row=last_row, column=col)
            cell.border = Border(
                left=cell.border.left, right=cell.border.right, top=cell.border.top,
                bottom=Side(style="medium", color="000000")
            )

    # Black borders between email groups
    for email_id in email_order:
        first_col = email_cond_col_map[email_id][all_conditions[0]]
        last_col  = email_cond_col_map[email_id][all_conditions[-1]]
        for row in range(1, cs.max_row + 1):
            lc = cs.cell(row=row, column=first_col)
            rc = cs.cell(row=row, column=last_col)
            lc.border = Border(left=BLACK_SIDE, right=lc.border.right if lc.border else Side())
            rc.border = Border(left=rc.border.left if rc.border else Side(), right=BLACK_SIDE)

    cs.column_dimensions["A"].width = 12
    cs.column_dimensions["B"].width = 18
    for i in range(3, col_start):
        cs.column_dimensions[get_column_letter(i)].width = 14
    cs.row_dimensions[1].height = 60
    cs.row_dimensions[2].height = 30
    cs.freeze_panes = "C3"

# ── Legend ─────────────────────────────────────────────────────────────────────
ls = wb.create_sheet("Legend")
legend_data = [
    ("Color",                     "Meaning"),
    ("Red email header",          "Phishing email (P) — scored on link clicks only"),
    ("Dark orange email header",  "Spam email (S) — not scored"),
    ("Green email header",        "Legitimate email (L) — not scored"),
    ("Green Score cell",          "Correct — did not click the link"),
    ("Red Score cell",            "Incorrect — clicked the link"),
    ("Red Clicked Link",          "Clicked a phishing link"),
    ("Light orange Clicked Link", "Clicked a spam link — flag for review"),
    ("Yellow Clicked Link",       "Clicked a legit link — informational"),
    ("Yellow Replied",            "Replied — informational"),
    ("Red Legit Flagged as Phish","Participant put a legit email in the Phishing folder"),
    ("", ""),
    ("Scoring",                   "Phishing only: Correct = did NOT click. Incorrect = clicked."),
    ("Spam",                      "Not scored. Link clicks flagged for review."),
    ("Legit",                     "Not scored. Clicks and replies tracked informational."),
    ("Legit Flagged as Phish",    "Count of legit emails moved to the Phishing folder specifically."),
    ("", ""),
    ("Totals section",            "Appears below participant rows at row 26."),
    ("Summary tab",               "Overall totals across all participants, one column per email."),
    ("By Condition tab",          "Same metrics broken out by condition group. Only shown when --conditions is passed."),
    ("Avg Phish Score",           "Average % of phishing emails not clicked, by condition."),
    ("", ""),
    ("--after 'YYYY-MM-DD'",      "Include participants who started on or after this date (Eastern)"),
    ("--before 'YYYY-MM-DD HH:MM'","Include participants who started before this date/time"),
    ("--conditions file.csv",     "CSV with RandID and Condition columns. Enables By Condition tab."),
    ("--output filename.xlsx",    "Custom output path"),
    ("Timezone",                  "EDT = UTC-4 (summer). Change EASTERN to UTC-5 for winter EST."),
]
for r, (a, b) in enumerate(legend_data, start=1):
    ls.cell(row=r, column=1, value=a).font = Font(name="Arial", bold=True, size=10)
    ls.cell(row=r, column=2, value=b).font = Font(name="Arial", size=10)
ls.column_dimensions["A"].width = 30
ls.column_dimensions["B"].width = 70

# Get output directory
OUTPUT_DIR = csv_path 
DESCRIPTION = 'results/CBDR_7-28'
# Add run date to output filenames
run_date = datetime.now().strftime('%Y-%m-%d')
DESCRIPTION = f'{DESCRIPTION}__{run_date}.xlsx'
out_path = DESCRIPTION
os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

wb.save(out_path)
print(f"✓ Saved to {out_path}")
print(f"  {len(rows)} participants × {len(email_order)} emails")
print(f"  Totals section starts at row {totals_start}")
if all_conditions:
    print(f"  By Condition tab: {len(all_conditions)} conditions")